apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: mycephrbd
provisioner: ceph.com/rbd
reclaimPolicy: Retain
parameters:
  monitors: 192.168.59.41:6789,192.168.59.42:6789
  adminId: k8s
  adminSecretName: ceph-k8s-secret
  adminSecretNamespace: kube-system
  pool: k8s
  userId: k8s
  userSecretName: ceph-k8s-secret
  imageFormat: "2"
  imageFeatures: layering
