apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - name: testvolume
      mountPath: /data/
      readOnly: false
  volumes:
  - name: testvolume
    persistentVolumeClaim:
      claimName: testpvc

